# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='filename',
            new_name='img_file',
        ),
    ]
